In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files

uploaded = files.upload()


df = pd.read_csv('feature_engineered_cleaned.csv')

print("Shape of original data:", df.shape)
df.head()

Saving feature_engineered_cleaned.csv to feature_engineered_cleaned (1).csv
Shape of original data: (964, 36)

,date,region,resource_type,usage_cpu,usage_storage,users_active,economic_index,cloud_market_demand,holiday,day_of_week,...,usage_storage_rolling_mean_30d,usage_storage_rolling_max_30d,usage_storage_rolling_min_30d,cpu_allocation,storage_allocation,utilization_ratio,storage_efficiency,weather,outages,price_changes
0,2023-01-10,East US,Container,86,779,380,90.92,0.86,0,1,...,1193.800000,1995.0,501.0,100,2000,0.86,0.3895,14.463458,1,-1.719991
1,2023-01-11,East US,VM,97,1562,369,114.66,0.98,0,2,...,1180.566667,1995.0,501.0,100,2000,0.97,0.7810,25.485811,0,-1.662741
2,2023-01-11,East US,Storage,75,1420,212,114.66,0.98,0,2,...,1174.733333,1995.0,501.0,100,2000,0.75,0.7100,13.744501,0,0.427115
3,2023-01-11,East US,Container,56,535,372,114.66,0.98,0,2,...,1171.866667,1995.0,501.0,100,2000,0.56,0.2675,25.345380,0,-0.552322
4,2023-01-12,East US,VM,92,943,300,100.68,0.86,0,3,...,1154.733333,1995.0,501.0,100,2000,0.92,0.4715,17.317966,1,-0.261856

In [3]:
# Cell 3: OPTIONAL – Sort by time column if needed

# Replace 'date' with your actual datetime column name if you have one.
# If you don't have a datetime column or it's already sorted by time, you can skip this cell.

# Example:
# df['date'] = pd.to_datetime(df['date'])
# df = df.sort_values('date').reset_index(drop=True)

# For now, we'll assume it's already in correct time order
df = df.reset_index(drop=True)

print("Data after optional sorting (showing top 5 rows):")
df.head()

Data after optional sorting (showing top 5 rows):

,date,region,resource_type,usage_cpu,usage_storage,users_active,economic_index,cloud_market_demand,holiday,day_of_week,...,usage_storage_rolling_mean_30d,usage_storage_rolling_max_30d,usage_storage_rolling_min_30d,cpu_allocation,storage_allocation,utilization_ratio,storage_efficiency,weather,outages,price_changes
0,2023-01-10,East US,Container,86,779,380,90.92,0.86,0,1,...,1193.800000,1995.0,501.0,100,2000,0.86,0.3895,14.463458,1,-1.719991
1,2023-01-11,East US,VM,97,1562,369,114.66,0.98,0,2,...,1180.566667,1995.0,501.0,100,2000,0.97,0.7810,25.485811,0,-1.662741
2,2023-01-11,East US,Storage,75,1420,212,114.66,0.98,0,2,...,1174.733333,1995.0,501.0,100,2000,0.75,0.7100,13.744501,0,0.427115
3,2023-01-11,East US,Container,56,535,372,114.66,0.98,0,2,...,1171.866667,1995.0,501.0,100,2000,0.56,0.2675,25.345380,0,-0.552322
4,2023-01-12,East US,VM,92,943,300,100.68,0.86,0,3,...,1154.733333,1995.0,501.0,100,2000,0.92,0.4715,17.317966,1,-0.261856

In [4]:


n = len(df)
train_end = int(0.7 * n)
val_end = int(0.9 * n)

train_df = df.iloc[:train_end]
val_df   = df.iloc[train_end:val_end]
test_df  = df.iloc[val_end:]

print("Total rows:", n)
print("Train rows:", len(train_df))
print("Validation rows:", len(val_df))
print("Test rows:", len(test_df))

Total rows: 964
Train rows: 674
Validation rows: 193
Test rows: 97

In [5]:


train_df = train_df.copy()
val_df = val_df.copy()
test_df = test_df.copy()

train_df['split'] = 'train'
val_df['split']   = 'val'
test_df['split']  = 'test'

dataset_df = pd.concat([train_df, val_df, test_df], axis=0).reset_index(drop=True)

print(dataset_df['split'].value_counts())
dataset_df.head()

split
train    674
val      193
test      97
Name: count, dtype: int64

,date,region,resource_type,usage_cpu,usage_storage,users_active,economic_index,cloud_market_demand,holiday,day_of_week,...,usage_storage_rolling_max_30d,usage_storage_rolling_min_30d,cpu_allocation,storage_allocation,utilization_ratio,storage_efficiency,weather,outages,price_changes,split
0,2023-01-10,East US,Container,86,779,380,90.92,0.86,0,1,...,1995.0,501.0,100,2000,0.86,0.3895,14.463458,1,-1.719991,train
1,2023-01-11,East US,VM,97,1562,369,114.66,0.98,0,2,...,1995.0,501.0,100,2000,0.97,0.7810,25.485811,0,-1.662741,train
2,2023-01-11,East US,Storage,75,1420,212,114.66,0.98,0,2,...,1995.0,501.0,100,2000,0.75,0.7100,13.744501,0,0.427115,train
3,2023-01-11,East US,Container,56,535,372,114.66,0.98,0,2,...,1995.0,501.0,100,2000,0.56,0.2675,25.345380,0,-0.552322,train
4,2023-01-12,East US,VM,92,943,300,100.68,0.86,0,3,...,1995.0,501.0,100,2000,0.92,0.4715,17.317966,1,-0.261856,train

In [6]:
dataset_df.to_csv('dataset.csv', index=False)
print("dataset.csv saved.")

from google.colab import files
files.download('dataset.csv')

dataset.csv saved.

In [7]:
train_df.to_csv('train.csv', index=False)
val_df.to_csv('val.csv', index=False)
test_df.to_csv('test.csv', index=False)

print("train.csv, val.csv, and test.csv saved.")

files.download('train.csv')
files.download('val.csv')
files.download('test.csv')

train.csv, val.csv, and test.csv saved.